Open Energy Dashboard Portfolio
oss-slu/oss-slu.github.io pull request #101
Opened 2024-08-25 03:47 UTC by Rakesh-Ranga-Buram

2024-08-29 20:27 UTC, kungfuchicken requested changes
you're making progress.

2024-08-29 20:27 UTC, kungfuchicken commented on docs/portfolio.md
> +**[Open Energy Dashboard](project_open_energy_dashboard/about.md)** - Open Energy Dashboard is a user-friendly way to display energy information from smart energy meters or uploaded via CSV files.
Please move this to the External Projects section that @MutyaSowmya123 created. It's merged into main, so you can either merge main into your branch or rebase your branch off of main to get this section.

2024-08-29 20:27 UTC, kungfuchicken commented on docs/project_open_energy_dashboard/about.md
> +
Please add as much detail in the ### Information section as you can. It doesn't need to have everything, but there are things you know (repo URL, client, tech lead, adoption date, technologies used, type, license).

2024-09-03 20:21 UTC, Rakesh-Ranga-Buram commented
Added the requested changes. @kungfuchicken can you please review this PR?

2024-09-05 23:17 UTC, kungfuchicken approved these changes
good enough for now.

2024-09-05 23:17 UTC, merged