Added portfolio for rerum admin work
oss-slu/oss-slu.github.io pull request #105
Opened 2024-08-25 05:24 UTC by alar12

Updated portfolio.md and created a dedicated folder for rerum admin work

2024-08-29 20:39 UTC, kungfuchicken requested changes
making progress, and almost there.

2024-08-29 20:39 UTC, kungfuchicken commented on docs/portfolio.md
> +**[Rerum Admin Work](project_rerum_admin_work/about.md)** - A tiny NodeJS web application for connecting with the RERUM API. This is for software developers looking to develop a client application th
Please move this to the External Projects section that @MutyaSowmya123 created. It's merged into main, so you can either merge main into your branch or rebase your branch off of main to get this section.

2024-08-29 20:39 UTC, kungfuchicken commented on docs/project_rerum_admin_work/about.md
> +### **Architecture**
Please restructure this as a paragraph of text under a "Technical Overview" section to match the structure of other existing pages. See https://oss-slu.github.io/docs/project_pi4micronaut/about and https://oss-slu.github.io/docs/project_wheres_religion_mobile/about for examples of the sort of format. Consistency in this format is important for branding.

2024-08-29 20:40 UTC, kungfuchicken commented on docs/project_rerum_admin_work/about.md
> +### **Architecture**
to be clear, the mermaid diagram is fine. i'm talking about the multiple bulleted lists from lines 66-91.

2024-09-09 20:57 UTC, kungfuchicken commented
I don't want to lose this great writeup (you used Mermaid!!!), but since we're pausing on this I don't want to merge it, either. i will leave this open  until we actually start working on it.

2024-09-09 22:06 UTC, alar12 commented
> I don't want to lose this great writeup (you used Mermaid!!!), but since we're pausing on this I don't want to merge it, either. i will leave this open until we actually start working on it.

That’s okay professor we will deal with this later when we start working on it again.

2024-12-17 19:59 UTC, kungfuchicken commented
I'm not sure if/when we'll start this project. I'm closing this for now. It's up to the next Tech Lead who works on it to start their own.

2024-12-17 19:59 UTC, closed without merging