Added about page for project_MDMA
oss-slu/oss-slu.github.io pull request #108
Opened 2024-08-30 03:48 UTC by Anjali0407-git

2024-08-30 15:16 UTC, kungfuchicken requested changes
This is all nearly perfect. Two minor things:
1. Let's get all the contributors to the original project listed. We can use the GH commit and PR history to get all of them, and we be able to get their GH profile links from there, too.
2. Please add this to the main portfolio page under the External Projects section.

2024-08-30 16:25 UTC, Anjali0407-git commented
Sure Daniel, I would add all contributors along with their GH profiles.
Also I would add the project to Portfolio page.

2024-09-01 15:57 UTC, Anjali0407-git commented on docs/portfolio.md
> +**[Where's Religion Mobile](project_wheres_religion_mobile/about.md)** - This Project is to create an application for ethnographers to capture the events happening around them along with some audio/v
@kungfuchicken the above changes are just trivial and are added by my Prettify extension.

2024-09-01 15:58 UTC, Anjali0407-git commented on docs/project_MDMA/about.md
> +  - Lalith Adithya Reddy Avuthu [<img src="/img/github.svg" alt="github" width="25" height="25" />](https://github.com/alar12)
@kungfuchicken added the details of all contributors to the main branch

2024-09-03 16:47 UTC, kungfuchicken approved these changes
follow up todo: clone the old repo into the OSS org, and change the `**Source Code:**` link.

2024-09-03 16:47 UTC, kungfuchicken commented on docs/project_MDMA/about.md
> +- **Source Code:** [https://github.com/slu-csci-5030/material-donor-mutual-assist/](https://github.com/slu-csci-5030/material-donor-mutual-assist/) [<img src="/img/git-alt.svg" alt="git" width="25" h
This repo will not be available to outsiders. We should clone this into the OSS organization. I'll merge it for now, but let's follow up with an edit once that's done.

2024-09-03 16:48 UTC, merged