Step time biofeedback (StepTB)
oss-slu/oss-slu.github.io pull request #113
Opened 2024-08-31 02:30 UTC by jsvoo

Incuded StepTB about information on the Portfolio page and added StepTB portfolio page according to issue #112

StepTB About page Update
<img width="640" alt="image" src="https://github.com/user-attachments/assets/7ffac467-9e20-4007-83f4-cf80cbf5c7e7">

StepTB Portfolio Page
<img width="640" alt="image" src="https://github.com/user-attachments/assets/b272eacc-7d8c-4d0b-b77d-e70b82e2efc7">

2024-09-03 16:54 UTC, kungfuchicken requested changes
almost there!

2024-09-03 16:54 UTC, kungfuchicken commented on docs/project_step_time_biofeedback/100x100.jpg
This is the logo for Seeing Is Believing. We can remove any logo until we identify a new logo, but we probably shouldn't re-use that one here.

2024-09-03 16:54 UTC, kungfuchicken commented on docs/project_step_time_biofeedback/about.md
> +- **Adoption Date:** TBD
Adoption date would be same as start date, since this is a greenfield project.

2024-09-03 17:22 UTC, jsvoo commented
@kungfuchicken Both changes have been implemented.

2024-09-05 23:20 UTC, kungfuchicken approved these changes
lgtm;

2024-09-05 23:20 UTC, merged