Ruthvik presentation
oss-slu/oss-slu.github.io pull request #68
Opened 2024-04-16 17:48 UTC by yashb196

Hello Everyone, I have added the report for the presentation by @ruthvikm  on April 5th at the pius library please do have a look at it and do let me know if there is any feedback needed on that regard

2024-04-16 18:52 UTC, ruthvikm commented on blog/2024-04-05-pi4micronaut.md
> +**Who:** Presentedy by [Ruthvik Mannem](https://github.com/ruthvikm), MS student in Computer Science<br/>
MS student in Artificial Intelligence

2024-04-16 18:53 UTC, ruthvikm commented on blog/2024-04-05-pi4micronaut.md
> +Ruthvik Mannem, a second year Masters student in Computer Science and a Research Assistant with Open Source with SLU, Explained about how he had created a library for micronaut which worked on Java i
Masters student in Artificial Intelligence

2024-04-16 18:58 UTC, ruthvikm requested changes
Requesting to change few typos. Also "OpenSourcewithSLU" is a single word as per Daniel's previous review.

2024-04-16 19:56 UTC, ruthvikm submitted a review, later dismissed

2024-04-16 19:59 UTC, kungfuchicken commented
> Requesting to change few typos. Also "OpenSourcewithSLU" is a single word as per Daniel's previous review.

should be "Open Source with SLU"

2024-04-16 21:01 UTC, kungfuchicken requested changes
looks great! there are a few small edits i'd like.

2024-04-16 21:01 UTC, kungfuchicken commented on blog/2024-04-05-pi4micronaut.md
> +Ruthvik Mannem, a second year Masters student in Artificial Intelligence and a Research Assistant with OpenSourcewithSLU, Explained about how he had created a library for micronaut which worked on Ja
Micronaut should be capitalized. I think this maybe should read "to communicate with the Micronaut library." (end with "library" and put the period before the inline image.) 

"up to"

"as an [example]"

2024-04-16 21:02 UTC, kungfuchicken commented on blog/2024-04-05-pi4micronaut.md
> +Ruthvik Mannem, a second year Masters student in Artificial Intelligence and a Research Assistant with OpenSourcewithSLU, Explained about how he had created a library for micronaut which worked on Ja
maybe "Micronaut framework" instead :D

2024-04-24 15:37 UTC, kungfuchicken approved these changes
lgtm; 🚀

2024-04-24 15:37 UTC, merged